name: CI

on:
  push:
    branches: [master, feature/ci]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: generate tag and release body
        run: |
          git config user.name github-ci
          git config user.email iiegor@users.noreply.github.com
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm test
      - run: npm run version
